### ISSUE TITLE
What's the difference to node-red-contrib-ccu

### ISSUE THREAD

**Issue by uli-rpi** [ptweety/node-red-contrib-ccu#10]
Sorry for the question,
but what's the difference between **node-red-contrib-ccu** and **@ptweety/node-red-contrib-ccu**  ?

**Comment by uli-rpi** [comment]
I found it -> closed

**Comment by dewenni** [comment]
@uli-rpi 
could you please give me a hint about the difference?

**Comment by uli-rpi** [comment]
I don't know the difference. I've since switched to Home Assistant and the question has become obsolete for me.
