### ISSUE TITLE
Homematic Write Level Value

### ISSUE THREAD

**Issue by geforce28** [ptweety/node-red-contrib-ccu#11]
I'm trying to write the "Level" value of a Homematic heating thermostat. (eTRV-E)

I can read the values.
These are from 0.0-1.0

For example, if I want to write 0.2, the message comes up in Nodered-Debug:
"rpc > HmIP-RF setValue ["xxxxxxxxxx:1","LEVEL",{"explicitDouble":0.2}] < Error: XML-RPC fault: Generic error (RESPONSE_NAK)"

**Comment by ptweety** [comment]
My own testing shows no such problems with neither `ccu-value` or `ccu-set-value` nodes.
Can you please share you Flow?
