### ISSUE TITLE
Anbindung CCU mit CCU-Jack funktioniert nicht

### ISSUE THREAD

**Issue by guenter-ms** [ptweety/node-red-contrib-ccu#12]
Hallo ptweety,

leider gelingt mir die connection zur CCU nicht. Ich möchte die CCU-Jack Integration gerne nutzen, bekomme aber die Verbindung nicht hin.

Alle Details sind unter https://homematic-forum.de/forum/viewtopic.php?f=85&t=80408&p=782964#p782964 beschrieben.

Würde mich sehr freuen, wenn du da mal reinguckst.

Viele Grüße
guenni

**Comment by ptweety** [comment]
Ich habe mir das Thema im Forum angesehen und kann dein Problem nicht reproduzieren. U.a. weil ich deine etwas komplizierte Integration mit HomeAssistant nicht habe.

**Comment by guenter-ms** [comment]
Ergebnis siehe: https://github.com/mdzio/ccu-jack/issues/153
