### ISSUE TITLE
HMIP HmIP-SMI55-2 als Device hinzufügen?

### ISSUE THREAD

**Issue by sebastianmachon** [ptweety/node-red-contrib-ccu#8]
Hallo,
erstmal vielen Dank, dass das Projekt übernommen wurde, so dass es weiter leben kann.

Leider ist der HmIP-SMI55-2 nicht verfügbar, so wie es aussieht.
Bei mir wird er nicht aus der CCU übernommen.

Liegt hier ein Fehler bei mir vor, oder ist der Aktor nicht im Code implementiert?

**Comment by ptweety** [comment]
Hi @sebastianmachon,

in der mitgelieferten `paramsets.json` ist dieses Gerät tatsächlich noch nicht aufgeführt.

Ich gehe mal davon aus, dass du eine bestehende Installation mit bereits laufendem Node-RED hattest und dann erst das Gerät neu hinzugefügt hast? Korrekt?

**Comment by sebastianmachon** [comment]
Hi @ptweety,

genau. Ich habe das Gerät in eine vorhandene Umgebung hinzugefügt.
Heute habe ich auf deine node-red-contrib-ccu gewechselt.

Bei dem Wechsel war der Aktor in der CCU natürlich schon vorhanden.

**Comment by ptweety** [comment]
Ok, ich bin noch nicht 100% durch den code gestiegen, aber aus meiner Sicht läuft es wie folgt mit der `paramsets.json`:

- es wird eine Basis-Version als Startpunkt bei der Installation mitgeliefert
- mit dem ersten Start des konfigurierten config-nodes `ccu-connection` wird aus der bestehenden Installation und den dort vorhandenen Geräten eine lokale Version generiert und im userdir der Node-RED Installation abgelegt

Das funktioniert ab diesem Zeitpunkt ganz gut; allerdings werden nachträglich hinzugefügte, neue Gerätetypen dadurch nicht erkannt.

Ich schlage folgendes Vorgehen vor:
- stoppe deine Node-RED Instanz
- benenne in deiner lokalen Installation die `paramsets.json` im `userdir` um
- starte Node-Red und warte ca. 10 min
- es sollte nun eine neue `paramsets.json` mit all deinen Geräten im `userdir` erstellt worden sein

Ab dann sollte das Gerät auch gefunden werden. (ggfs. nochmal einen Neustart von Node-RED machen)

Um allerdings das Problem auch für andere Nutzer zu lösen, wäre es schön, wenn du mir deine `paramsets.json` per mail sendest. Dann kann ich die mitgelieferte Basis-Version entsprechend aktualisieren.

PS: der Ort des `userdir` kommt auf deine Installation an.

**Comment by sebastianmachon** [comment]
Alles klar, dann werde ich mein Glück mal probieren und dir Bescheid geben.
Wird aber frühestens Mittwoch etwas.

**Comment by sebastianmachon** [comment]
So, habe deine Steps jetzt abgearbeitet.

Dabei ist mir aufgefallen, dass bei mir der SMI55-2 bereits in der paramsets.json enthalten war.
Ich kann dir aber gerne beide Files zuschicken. Verrätst du mir wo ich deine Mailadresse finde?

Geändert hat sich bei mir dahingehend nichts, dass der SMI55-2 weiterhin nicht in Node-RED und HomeKit verfügbar ist.

**Comment by ptweety** [comment]
Die steht in der `package.json` ;)

```
    "author": {
        "name": "ptweety (Matthias)",
        "email": "me@ptweety.net"
```

**Comment by ptweety** [comment]
Danke. Die mail ist angekommen.

Jetzt muss ich aber doch genauer nachfragen:

- Wo genau hast du reingeschaut und festgestellt, dass der HMiP-SMI55-2 nicht gefunden wird?
- Also, welchen Node hast du genutzt, welche Interfaces sind ausgewählt und welche Eingaben hast du vorgenommen?

Kannst du das bitte Schritt für Schritt beschreiben?

**Comment by sebastianmachon** [comment]
In Node-RED bin ich in meinem Flow.
Darin wähle ich meinen „Homematic“ Node aus.
Anschließend sehe ich die Liste der in der CCU eingerichtetenGeräte. Darin fehlt der SMI55-2

Siehe die beiden Screenshots:

![FEA4EDE1-C15D-46E7-8B9A-DA434F99F62E](https://user-images.githubusercontent.com/56752740/201193762-8cf0cace-cee9-45a2-96ef-b040ae54479b.jpeg)
![4750DB1E-9225-4259-A50B-E1630DB37E5F](https://user-images.githubusercontent.com/56752740/201193766-b5ad3a51-0968-4e7c-b50e-e5549c2f9a82.jpeg)

**Comment by ptweety** [comment]
Ahh,

der `Homematic` Node gehört gar nicht zu `node-red-contrib-ccu`, sondern zu `RedMatic-Homekit`. Schau doch bitte mal in den `rpc event` Node rein. Dort sollte das Gerät auftauchen.

Dann sehen wir mal weiter ...

**Comment by sebastianmachon** [comment]
Oh man… das habe ich nicht berücksichtigt…

Im rpc Event ist er drin…

**Comment by ptweety** [comment]
Alles gut.

Dann schau nun mal in das `node_modules` Verzeichnis deiner Installation und suche nach [RedMatic-HomeKit](https://github.com/rdmtc/RedMatic-HomeKit)/[homematic-devices](https://github.com/rdmtc/RedMatic-HomeKit/tree/master/homematic-devices)/hmip-smi55.js

Lege daneben eine Datei `hmip-smi55-2.js` mit diesem Inhalt an:

```
module.exports = require('./hmip-smi55.js');
```

und starte Node-RED mal neu.

**Comment by sebastianmachon** [comment]
Vielen Dank! Das war die Lösung.

Nach dem Neustart ist das Gerät direkt verfügbar gewesen.
