### ISSUE TITLE
Documentation on ccu-mqtt

### ISSUE THREAD

**Issue by JMyrng** [ptweety/node-red-contrib-ccu#9]
Hi there, 

thanks for maintaining this awesome software. 

My hole smarthome is based on MQTT and I'd like to talk to the CCU3 with MQTT too. 
Getting variables out works like a charm with the "ccu-mqtt" but I can't find a documentation on this input sceme. Where can I find the proper topics for setting some params in the CCU3?

Setup: NodeRed in Docker on Synology NAS, CCU3 for floor heating

Best regards,
Myrng

**Comment by ptweety** [comment]
> My hole smarthome is based on MQTT and I'd like to talk to the CCU3 with MQTT too.

In this case I would strongly recommend the [CCU-Jack](https://github.com/mdzio/ccu-jack) as an add-on for your CCU

**Comment by JMyrng** [comment]
There are two things that bother me about this solution: 
1. I would like to run the CCU without additional software. 
2. CCU-Jack creates its own MQTT server, but I would like to use it with an existing server.

Where can I find information about this topic sceme: 
`hm/set/${channelNameOrAddress}/${datapoint}`
Is it copied from CCU-Jack?

**Comment by ptweety** [comment]
> 1. I would like to run the CCU without additional software.

Fair enough. As you can setup Node-RED within it's own docker container on your NAS the same applies to CCU-Jack.

> 2. CCU-Jack creates its own MQTT server, but I would like to use it with an existing server.

As far as I know CCU-Jack can also act as a MQTT-Bridge.

> Where can I find information about this topic sceme: `hm/set/${channelNameOrAddress}/${datapoint}` Is it copied from CCU-Jack?

No, it's not from CCU-Jack. I think it was made up by the original author of this node years ago ... See [here](https://github.com/mqtt-smarthome/mqtt-smarthome)

**Comment by JMyrng** [comment]
Thank you for your quick answers. 

I've got it working on my side with the ccu-mqtt node. 

In case anyone is ever looking for a similar solution:
To set the heating profile on a WTH-2 thermostat via ccu-mqtt node: 
1. ccu-mqtt node settings for setValue `hm/set/${channelNameOrAddress}/${datapoint}`
where `channelNameOrAddress` is the serial number with the according channel, e.g. `000A9D8XXXXX41:1`
and `datapoint` is `ACTIVE_PROFILE`
The name of the datapoint can be sourced in the outgoing mqtt messages of the device
3. set up a mqtt-in node in front of the ccu-mqtt node with the topic `hm/set/#`
4. just send the new profile number to the topic `hm/set/000A9D8XXXXX41:1/ACTIVE_PROFILE`

In my opinion, this is about as easy as it gets. Thank you again for this awesome module @ptweety!
